export const states = [
  { id: 1, name: "Acre", tax: 7 },
  { id: 2, name: "Alagoas", tax: 7 },
  { id: 3, name: "Amapá", tax: 7 },
  { id: 4, name: "Amazonas", tax: 7 },
  { id: 5, name: "Bahia", tax: 7 },
  { id: 6, name: "Ceará", tax: 7 },
  { id: 7, name: "Distrito Federal" },
  { id: 8, name: "Espírito Santo", tax: 7 },
  { id: 9, name: "Goiás", tax: 7 },
  { id: 10, name: "Maranhão", tax: 7 },
  { id: 11, name: "Mato Grosso", tax: 7 },
  { id: 12, name: "Mato Grosso do Sul", tax: 7 },
  { id: 13, name: "Minas Gerais", tax: 12 },
  { id: 14, name: "Pará", tax: 7 },
  { id: 15, name: "Paraíba", tax: 7 },
  { id: 16, name: "Paraná", tax: 12 },
  { id: 17, name: "Pernambuco", tax: 7 },
  { id: 18, name: "Piauí", tax: 7 },
  { id: 19, name: "Rio de Janeiro", tax: 12 },
  { id: 20, name: "Rio Grande do Norte", tax: 7 },
  { id: 21, name: "Rio Grande do Sul", tax: 12 },
  { id: 22, name: "Rondônia", tax: 7 },
  { id: 23, name: "Roraima", tax: 7 },
  { id: 24, name: "Santa Catarina", tax: 12 },
  { id: 25, name: "São Paulo", tax: 12 },
  { id: 26, name: "Sergipe", tax: 7 },
  { id: 27, name: "Tocantins", tax: 7 },
];
